// GENERATED by scripts/gen-families.mjs from openapi.yaml v0.6.0 — do not edit.
// Regenerate with `npm run gen:families`; src/api/families.generated.test.ts
// fails when this file and the contract disagree.
//
// A family is a contract tag, and it is the unit the adopter answers on
// (mine / mock / hide) — see src/lib/families.ts for what the answers do.

export const FAMILIES = [
  "auth",
  "identity",
  "admin",
  "meta",
  "trees",
  "agents",
  "conversations",
  "memory",
  "chat",
  "replay",
  "trace",
  "tasks",
  "datasets",
  "judging",
  "settings",
] as const;

export type Family = (typeof FAMILIES)[number];

// What each family MEANS is not repeated here: the generator's questionnaire
// reads the tag descriptions straight out of openapi.yaml
// (scripts/conformance.mjs familyDescriptions). Copying them into src/ would
// also drag the contract's prose past the invariant guards in tests/.

/**
 * Contract path -> family, ordered so the first match wins: a literal segment
 * beats a parameter one (/eval/cases/import before /eval/cases/{case_id}).
 */
const ROUTES: ReadonlyArray<readonly [RegExp, Family]> = [
  [/^\/admin\/generator\/status$/, "admin"], // /admin/generator/status
  [/^\/admin\/conversations$/, "admin"], // /admin/conversations
  [/^\/eval\/cases\/import$/, "datasets"], // /eval/cases/import
  [/^\/admin\/generator$/, "admin"], // /admin/generator
  [/^\/eval\/benchmarks$/, "datasets"], // /eval/benchmarks
  [/^\/eval\/judgments$/, "judging"], // /eval/judgments
  [/^\/eval\/rubrics$/, "judging"], // /eval/rubrics
  [/^\/tasks\/stream$/, "tasks"], // /tasks/stream
  [/^\/admin\/users$/, "admin"], // /admin/users
  [/^\/auth\/logout$/, "auth"], // /auth/logout
  [/^\/agenttrees$/, "trees"], // /agenttrees
  [/^\/auth\/token$/, "auth"], // /auth/token
  [/^\/eval\/cases$/, "datasets"], // /eval/cases
  [/^\/eval\/judge$/, "judging"], // /eval/judge
  [/^\/feedback$/, "chat"], // /feedback
  [/^\/settings$/, "settings"], // /settings
  [/^\/healthz$/, "meta"], // /healthz
  [/^\/models$/, "meta"], // /models
  [/^\/upload$/, "chat"], // /upload
  [/^\/tasks$/, "tasks"], // /tasks
  [/^\/me$/, "identity"], // /me
  [/^\/eval\/evaluations\/[^/]+\/summary$/, "judging"], // /eval/evaluations/{evaluationId}/summary
  [/^\/eval\/benchmarks\/[^/]+\/versions$/, "datasets"], // /eval/benchmarks/{benchmarkId}/versions
  [/^\/eval\/benchmarks\/[^/]+\/freeze$/, "datasets"], // /eval/benchmarks/{benchmarkId}/freeze
  [/^\/eval\/benchmarks\/[^/]+\/replay$/, "datasets"], // /eval/benchmarks/{benchmarkId}/replay
  [/^\/eval\/benchmarks\/[^/]+\/items$/, "datasets"], // /eval/benchmarks/{benchmarkId}/items
  [/^\/admin\/users\/[^/]+\/permissions$/, "admin"], // /admin/users/{userId}/permissions
  [/^\/agenttrees\/[^/]+\/memory\/compact$/, "memory"], // /agenttrees/{tree}/memory/compact
  [/^\/eval\/rubrics\/[^/]+\/versions$/, "judging"], // /eval/rubrics/{rubricId}/versions
  [/^\/agenttrees\/[^/]+\/conversations$/, "conversations"], // /agenttrees/{tree}/conversations
  [/^\/agenttrees\/[^/]+\/evaluations$/, "replay"], // /agenttrees/{tree}/evaluations
  [/^\/agenttrees\/[^/]+\/replay\/turn$/, "replay"], // /agenttrees/{tree}/replay/turn
  [/^\/eval\/benchmarks\/[^/]+$/, "datasets"], // /eval/benchmarks/{benchmarkId}
  [/^\/eval\/cases\/[^/]+\/versions$/, "datasets"], // /eval/cases/{caseId}/versions
  [/^\/agenttrees\/[^/]+\/endpoints$/, "trees"], // /agenttrees/{tree}/endpoints
  [/^\/tasks\/[^/]+\/retry-failed$/, "tasks"], // /tasks/{taskId}/retry-failed
  [/^\/admin\/agenttrees\/[^/]+$/, "admin"], // /admin/agenttrees/{treeId}
  [/^\/agenttrees\/[^/]+\/agents$/, "agents"], // /agenttrees/{tree}/agents
  [/^\/agenttrees\/[^/]+\/memory$/, "memory"], // /agenttrees/{tree}/memory
  [/^\/agenttrees\/[^/]+\/replay$/, "replay"], // /agenttrees/{tree}/replay
  [/^\/agenttrees\/[^/]+\/chat$/, "chat"], // /agenttrees/{tree}/chat
  [/^\/spans\/[^/]+\/payload$/, "trace"], // /spans/{spanId}/payload
  [/^\/eval\/cases\/[^/]+$/, "datasets"], // /eval/cases/{caseId}
  [/^\/tasks\/[^/]+$/, "tasks"], // /tasks/{taskId}
  [/^\/agenttrees\/[^/]+\/agents\/[^/]+\/instructions\/versions$/, "agents"], // /agenttrees/{tree}/agents/{agentId}/instructions/versions
  [/^\/agenttrees\/[^/]+\/conversations\/[^/]+\/turns$/, "conversations"], // /agenttrees/{tree}/conversations/{conversationId}/turns
  [/^\/agenttrees\/[^/]+\/agents\/[^/]+\/last-selection$/, "agents"], // /agenttrees/{tree}/agents/{agentId}/last-selection
  [/^\/agenttrees\/[^/]+\/conversations\/[^/]+$/, "conversations"], // /agenttrees/{tree}/conversations/{conversationId}
  [/^\/agenttrees\/[^/]+\/agents\/[^/]+\/instructions$/, "agents"], // /agenttrees/{tree}/agents/{agentId}/instructions
  [/^\/agenttrees\/[^/]+\/agents\/[^/]+\/snapshots$/, "agents"], // /agenttrees/{tree}/agents/{agentId}/snapshots
  [/^\/agenttrees\/[^/]+\/evaluations\/[^/]+$/, "replay"], // /agenttrees/{tree}/evaluations/{evaluationId}
  [/^\/agenttrees\/[^/]+\/turns\/[^/]+\/trace$/, "trace"], // /agenttrees/{tree}/turns/{turnId}/trace
];

/**
 * The family a request belongs to, from the CONTRACT path the client built
 * (query string excluded — buildUrl adds that separately). null = a path the
 * contract does not describe, which the caller must treat as un-answerable
 * rather than as any particular family.
 */
export function familyOfPath(path: string): Family | null {
  const bare = path.split(/[?#]/)[0];
  for (const [pattern, family] of ROUTES) {
    if (pattern.test(bare)) return family;
  }
  return null;
}
