import { useEffect, useState } from "react";
import { useNavigate } from "react-router";
import {
  Alert,
  Anchor,
  Badge,
  Button,
  Group,
  Loader,
  Modal,
  MultiSelect,
  Select,
  Stack,
  Text,
} from "@mantine/core";
import { api } from "../api/client";
import type { ReplayTurnAccepted, Variant } from "../api/types";
import { useAsync } from "../hooks/useAsync";
import { useApp } from "../AppContext";

// Turn re-fire as forks: "Re-fire one turn
// against several endpoints at once, each becoming a real new conversation you
// can open and continue in Chat — from any results cell or any chat turn".
// Semantics (feature-spec.md:68): "Each (turn × endpoint × config) forks a new
// conversation: original history up to that turn is copied, the turn is
// re-generated by the chosen endpoint, and the result is stored as a normal
// conversation." Fired via POST /agenttrees/{tree}/replay/turn
// (openapi.yaml:623-652) → 202 ReplayTurnAccepted: "one task_id + new
// conversation_id per endpoint" (feature-spec.md:71) + evaluation_id backing the
// fork pivot.
//
// Design choice — slim inline selects instead of RunConfigPanel: the sketches'
// fork affordance is a single glyph in a dense action row (clean/01-chat.svg
// "⑂⌁"; 04-results.svg "+ Re-run this turn with…"), so the modal keeps to the
// required endpoints multi-select (min 1, ReplayTurnRequest.endpoints
// openapi.yaml:1562-1566) plus the optional config pair model / instruction
// version (task brief; Variant openapi.yaml:1494-1503). RunConfigPanel would
// drag in agent picker + temperature + judge scaffolding and their fetches —
// too heavy for this compact surface; full multi-config evaluations stay in the Evaluations
// stepper. The version select renders only when the caller knows the agent
// (agentId prop) — instruction versions are agent-scoped.
//
// Async note: forks generate in the background. Open in Chat navigates
// immediately and shows whatever is persisted at click time (the copied
// history); the regenerated turn appears once its task completes — ChatPage
// has no live task-completion feed for non-streaming turns.

interface Props {
  /** Source of the re-fire — the turn whose (copied-history) forks are created. */
  conversationId: string;
  turnId: string;
  /** Enables the optional instruction-version select (versions are agent-scoped). */
  agentId?: string | null;
  opened: boolean;
  onClose: () => void;
}

// Fresh form per open WITHOUT a reset effect: Mantine's Modal does not render
// its children while closed (ModalBaseContent is a Transition mounted on
// `opened`), so the body mounts on open and its state starts at the
// initialisers every time. The key carries the OTHER half of the old effect's
// dependency list — a tree or agent change while the modal is open resets the
// form exactly as it used to.
export function ForkModal({ conversationId, turnId, agentId, opened, onClose }: Props) {
  const { tree } = useApp();
  return (
    <Modal
      opened={opened}
      onClose={onClose}
      title={<Text size="sm" fw={600}>⑂ Re-run this turn with…</Text>}
      size="sm"
    >
      <ForkBody
        key={`${tree}/${agentId ?? ""}`}
        conversationId={conversationId}
        turnId={turnId}
        agentId={agentId}
        onClose={onClose}
      />
    </Modal>
  );
}

function ForkBody({
  conversationId,
  turnId,
  agentId,
  onClose,
}: Omit<Props, "opened">) {
  const { tree, models, ensureModels, refreshConversations } = useApp();
  const navigate = useNavigate();

  const { data: endpoints, error: endpointsError } = useAsync(
    () => api.endpoints(tree),
    [tree],
  );
  // Optional axis — endpoints alone still fire, so a failure yields no versions
  // rather than an error.
  const { data: versions } = useAsync(
    agentId
      ? () =>
          api
            .instructions(tree, agentId)
            .then((h) => h.versions.map((v) => v.version))
            .catch(() => [] as number[])
      : null,
    [tree, agentId],
  );
  const [selected, setSelected] = useState<string[]>([]);
  const [model, setModel] = useState<string | null>(null);
  const [version, setVersion] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [firing, setFiring] = useState(false);
  const [accepted, setAccepted] = useState<ReplayTurnAccepted | null>(null);

  // Model list comes from the session cache; asking for it is the only thing
  // left that the old reset effect did beyond resetting.
  useEffect(() => {
    ensureModels();
  }, [ensureModels]);

  const endpointName = (id: string) => endpoints?.find((e) => e.id === id)?.name ?? id;

  const fire = async () => {
    setFiring(true);
    setError(null);
    // Optional config subset: only set axes go out; nothing set = no config
    // key (ReplayTurnRequest.config nullable, openapi.yaml:1567-1569).
    // agent_id rides along with instruction_version — versions are meaningless
    // without their agent (Variant, openapi.yaml:1494-1497).
    const config: Variant = {
      ...(model ? { model } : {}),
      ...(version != null ? { agent_id: agentId, instruction_version: Number(version) } : {}),
    };
    try {
      // context_policy is frozen-pinned inside api.replayTurn (client.ts) —
      // Phase 1 invariant (openapi.yaml:1570-1574).
      const res = await api.replayTurn(tree, {
        conversation_id: conversationId,
        turn_id: turnId,
        endpoints: selected,
        ...(Object.keys(config).length > 0 ? { config } : {}),
      });
      setAccepted(res);
      // Parent's "N forks" chip count changed — reload the sidebar list
      // (feature-spec.md:5 fork nesting; AppContext.conversationsVersion).
      refreshConversations();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setFiring(false);
    }
  };

  const go = (path: string) => {
    onClose();
    navigate(path);
  };

  return accepted ? (
    <Stack gap="xs" data-testid="fork-results">
      <Text size="xs" c="dimmed">
        Forks are generating in the background — Open in Chat shows the
        copied history now; the re-generated turn appears once its task
        completes.
      </Text>
      {/* "one task_id + new conversation_id per endpoint"
          (feature-spec.md:71); "Open in Chat: any fork can be opened in
          the main Chat page and continued there" (feature-spec.md:70). */}
      {accepted.results.map((r) => (
        <Group key={r.endpoint_id} justify="space-between" wrap="nowrap">
          <Group gap={6} wrap="nowrap">
            <Text size="sm">{endpointName(r.endpoint_id)}</Text>
            <Badge size="xs" variant="light" color="yellow">
              queued
            </Badge>
          </Group>
          <Anchor size="xs" onClick={() => go(`/chat/${r.conversation_id}`)}>
            Open in Chat ↗
          </Anchor>
        </Group>
      ))}
      <Group justify="space-between" mt={4}>
        {/* evaluation_id backs the fork-comparison pivot (openapi.yaml:1581-1585)
            — link to the existing evaluation detail route. */}
        <Anchor size="xs" onClick={() => go(`/studio/evaluations/${accepted.evaluation_id}`)}>
          View evaluation
        </Anchor>
        <Button size="xs" variant="default" onClick={onClose}>
          Close
        </Button>
      </Group>
    </Stack>
  ) : (
    <Stack gap="sm">
      {endpoints == null && !endpointsError && <Loader size="xs" mx="auto" />}
      {endpoints != null && (
        <MultiSelect
          size="xs"
          label="Endpoints"
          description="one fork per endpoint"
          placeholder={selected.length ? undefined : "Pick at least one"}
          data={endpoints.map((e) => ({ value: e.id, label: e.name }))}
          value={selected}
          onChange={setSelected}
          comboboxProps={{ withinPortal: false }}
        />
      )}
      <Select
        size="xs"
        label="Model (optional)"
        placeholder="unchanged"
        data={models?.map((m) => ({ value: m.id, label: m.name })) ?? []}
        value={model}
        onChange={setModel}
        clearable
        comboboxProps={{ withinPortal: false }}
      />
      {agentId != null && versions != null && versions.length > 0 && (
        <Select
          size="xs"
          label="Instruction version (optional)"
          placeholder="live"
          data={versions.map((v) => ({ value: String(v), label: `v${v}` }))}
          value={version}
          onChange={setVersion}
          clearable
          comboboxProps={{ withinPortal: false }}
        />
      )}
      {(error ?? endpointsError) && (
        <Alert color="red" title="Fork failed">
          {error ?? endpointsError?.message}
        </Alert>
      )}
      <Group justify="flex-end">
        <Button
          size="xs"
          disabled={selected.length === 0}
          loading={firing}
          onClick={() => void fire()}
        >
          Fork ⑂
        </Button>
      </Group>
        </Stack>
  );
}
